---
name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  PKG_NAME: coredns-ldap
  PKG_BINARY: coredns

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ env.PKG_NAME }}
        uses: actions/checkout@v3
        with:
          repository: 'coredns/coredns'
          ref: 'master'

      - name: Build and create archive
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports -y
          sudo apt update
          sudo apt install -y curl golang-go
          printf "\nldap:github.com/bbusse/coredns-ldap\nautoipv6ptr:github.com/vlcty/coredns-auto-ipv6-ptr\n" >> plugin.cfg
          go get github.com/vlcty/coredns-auto-ipv6-ptr
          go get github.com/bbusse/coredns-ldap
          go generate && go build
          tar -cJvf ${{ env.PKG_NAME }}-linux-amd64-latest.tar.xz ${{ env.PKG_BINARY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}-linux-amd64-latest
          path: ${{ env.PKG_NAME }}-linux-amd64-latest.tar.xz
